import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { Casilla } from '../interfaces/casilla';

@Component({
  selector: 'app-teclado',
  templateUrl: './teclado.component.html',
  styleUrls: ['./teclado.component.css'],
})
export class TecladoComponent implements OnInit {
  @Output() botonPulsado = new EventEmitter<string>();
  terminado = false;

  fila1 = ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'];
  fila2 = ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Ñ'];
  fila3 = ['Z', 'X', 'C', 'V', 'B', 'N', 'M'];
  filas = [this.fila1, this.fila2, this.fila3];

  casillas!: Casilla[][];
  palabraSecreta!: string[];
  indice_palabra!: number;
  letrasPulsadas = 0;

  turno: number = 0;

  casillaStyle = {
    border: '1px solid black',
    'min-height': '50px',
    'max-width': '50px'
  };

  constructor() {
    this.comenzarPartida();
  }

  registrarPulsacion(boton: string) {
    this.botonPulsado.emit(boton);
  }

  comenzarPartida(): void {
    this.turno = 0;
    this.letrasPulsadas = 0;
    this.indice_palabra = Math.floor(Math.random() * this.palabras.length);
    this.palabraSecreta = [...this.palabras[this.indice_palabra]];
    this.casillas = Array.from({ length: 6 }, () =>
      Array.from({ length: 5 }, () => ({ letra: ' ', estado: 0 }))
    );
    this.terminado = false;
  }

  comprobarLetra(letra: string): void {
    if (this.terminado || this.letrasPulsadas >= 5) {
      return;
    }
    this.casillas[this.turno][this.letrasPulsadas].letra = letra;
    this.letrasPulsadas++;
  }

  borrarLetra(): void {
    if (this.terminado || this.letrasPulsadas <= 0) {
      return;
    }
    this.casillas[this.turno][this.letrasPulsadas - 1].letra = ' ';
    this.letrasPulsadas--;
  }

  terminarTurno(): void {
    if (this.terminado || this.turno > 5 || this.letrasPulsadas < 5) {
      return;
    }
    let aciertos = 0;
    /*let letrasEvaluadas = this.palabraSecreta.reduce(
      (acumulado: { [key: string]: number }, actual: string) => {
        acumulado[actual] = (acumulado[actual] || 0) + 1;
        return acumulado;
      },
      {}
    );*/

    let letrasEvaluadas: { [key: string]: number } = {};
    for (let letra of this.palabraSecreta) {
      letrasEvaluadas[letra] = (letrasEvaluadas[letra] || 0) + 1;
    }

    let casillasPorComprobar: Casilla[] = [];
    for (let i = 0; i < this.palabraSecreta.length; i++) {
      let casilla = this.casillas[this.turno][i];
      let letra = casilla.letra;

      if (this.palabraSecreta[i] === casilla.letra.toLowerCase()) {
        casilla.estado = 1;
        aciertos++;
        letrasEvaluadas[letra.toLowerCase()]--;
      } else {
        casillasPorComprobar.push(casilla);
      }
    }

    for (let i = 0; i < casillasPorComprobar.length; i++) {
      let casilla = casillasPorComprobar[i];
      let letra = casilla.letra.toLowerCase();
      console.log(letrasEvaluadas[letra]);
      if (letrasEvaluadas[letra] && letrasEvaluadas[letra] >= 1) {
        casilla.estado = 2;
        letrasEvaluadas[letra]--;
      } else {
        casilla.estado = 3;
      }
    }

    this.turno++;
    this.letrasPulsadas = 0;

    this.terminado = aciertos >= 5 || this.turno > 5;
  }

  ngOnInit(): void {}

  palabras = [
    'abeto',
    'actor',
    'aguas',
    'agudo',
    'alado',
    'albas',
    'altar',
    'atizo',
    'avala',
    'avion',
    'azul',
    'abaco',
    'abate',
    'abeja',
    'aboya',
    'abran',
    'abras',
    'abría',
    'acoja',
    'acojo',
    'acres',
    'actas',
    'actos',
    'actuo',
    'acuna',
    'acune',
    'acuso',
    'acuña',
    'afeas',
    'aguda',
    'agudo',
    'alaju',
    'alces',
    'aldea',
    'aleja',
    'algas',
    'alias',
    'almas',
    'altos',
    'amina',
    'andas',
    'andes',
    'anear',
    'anima',
    'atojo',
    'ayuda',
    'azote',
    'aerea',
    'añoro',
    'bache',
    'babas',
    'bajes',
    'balas',
    'bebes',
    'belen',
    'bicho',
    'bizco',
    'bueno',
    'buena',
    'busca',
    'bajos',
    'barre',
    'batas',
    'bates',
    'bayas',
    'bañas',
    'baños',
    'besen',
    'besos',
    'bojar',
    'bonos',
    'borre',
    'borra',
    'botad',
    'botes',
    'bruta',
    'bruto',
    'cabra',
    'cafes',
    'cajas',
    'calar',
    'calas',
    'calca',
    'calco',
    'calla',
    'calma',
    'camba',
    'campo',
    'canas',
    'canto',
    'capto',
    'caras',
    'carga',
    'cargo',
    'carro',
    'casas',
    'caída',
    'cejas',
    'cenas',
    'cepas',
    'cerca',
    'cerco',
    'cerdo',
    'cerda',
    'chile',
    'china',
    'ciego',
    'ciega',
    'cinco',
    'cines',
    'cisne',
    'citas',
    'clara',
    'claro',
    'clave',
    'clavo',
    'colas',
    'colon',
    'coral',
    'coras',
    'corea',
    'corro',
    'cosas',
    'costo',
    'coste',
    'crudo',
    'curdo',
    'curda',
    'curar',
    'celta',
    'coger',
    'combo',
    'corse',
    'crema',
    'cuida',
    'culos',
    'cural',
    'dados',
    'dagas',
    'datos',
    'daños',
    'danza',
    'dejar',
    'dejes',
    'denso',
    'densa',
    'dices',
    'divos',
    'dotes',
    'dunas',
    'dures',
    'duros',
    'enojo',
    'ellos',
    'ellas',
    'echas',
    'edito',
    'edita',
    'elevo',
    'enoje',
    'error',
    'errar',
    'estas',
    'emoji',
    'envio',
    'erizo',
    'espia',
    'euros',
    'fallo',
    'falto',
    'feria',
    'fetos',
    'fijos',
    'filas',
    'filia',
    'finca',
    'firma',
    'floto',
    'focos',
    'folla',
    'forma',
    'Frida',
    'frita',
    'frito',
    'freir',
    'fugas',
    'fumas',
    'fusil',
    'gafas',
    'galas',
    'galos',
    'ganas',
    'ganes',
    'gases',
    'gasto',
    'girar',
    'gerbo',
    'gordo',
    'gorda',
    'gorro',
    'gorra',
    'grave',
    'grava',
    'grito',
    'gemir',
    'güera',
    'güero',
    'hacer',
    'halos',
    'hasta',
    'harta',
    'harto',
    'heces',
    'hielo',
    'habas',
    'habla',
    'hacha',
    'hijas',
    'hijos',
    'huera',
    'huero',
    'india',
    'indio',
    'ideas',
    'inflo',
    'islas',
    'islas',
    'jefas',
    'jefes',
    'jerga',
    'juego',
    'jugar',
    'julio',
    'Julio',
    'jadeo',
    'jerbo',
    'jurar',
    'kurdo',
    'kurda',
    'labia',
    'lacra',
    'lados',
    'lagos',
    'lance',
    'larga',
    'largo',
    'lejos',
    'lenta',
    'lento',
    'libia',
    'libro',
    'libra',
    'linda',
    'lindo',
    'logro',
    'loteo',
    'luche',
    'liber',
    'mania',
    'malos',
    'malas',
    'marca',
    'marco',
    'marte',
    'medio',
    'melón',
    'menos',
    'meter',
    'metro',
    'molar',
    'moler',
    'monte',
    'morir',
    'manco',
    'manca',
    'malta',
    'mango',
    'manga',
    'meaba',
    'media',
    'midas',
    'miras',
    'mirar',
    'mirón',
    'mojar',
    'mosca',
    'multa',
    'mundo',
    'nacer',
    'nadar',
    'narro',
    'natas',
    'naves',
    'necio',
    'necia',
    'niños',
    'notas',
    'nubes',
    'nabos',
    'nazis',
    'ñoñez',
    'ñizca',
    'ñuzco',
    'ñoqui',
    'ñurdo',
    'ñurda',
    'opera',
    'obras',
    'ocios',
    'ollas',
    'ondas',
    'onzas',
    'otros',
    'otras',
    'ovulo',
    'oirte',
    'oreja',
    'odiar',
    'orina',
    'ortos',
    'osito',
    'palas',
    'pedir',
    'pelea',
    'pelos',
    'pelar',
    'peras',
    'perro',
    'perra',
    'pesos',
    'pilas',
    'pinto',
    'poder',
    'pacto',
    'pagar',
    'palma',
    'parda',
    'pardo',
    'paseo',
    'pateo',
    'pecio',
    'penes',
    'peres',
    'pesca',
    'pifia',
    'pisco',
    'playa',
    'pleno',
    'poner',
    'prada',
    'punto',
    'punta',
    'purga',
    'queda',
    'quedo',
    'quede',
    'quema',
    'quito',
    'queso',
    'quepa',
    'reloj',
    'rubio',
    'rubia',
    'rasco',
    'rasca',
    'ratas',
    'rasta',
    'ratos',
    'redes',
    'remar',
    'renos',
    'renta',
    'rabia',
    'rabos',
    'rabal',
    'ramón',
    'raspa',
    'recio',
    'recia',
    'regio',
    'regia',
    'resto',
    'rugir',
    'rogar',
    'sabio',
    'sabia',
    'savia',
    'saber',
    'sacar',
    'salar',
    'salir',
    'selva',
    'sanar',
    'sopas',
    'secar',
    'serio',
    'seria',
    'sitio',
    'sobar',
    'sonar',
    'subir',
    'sucio',
    'sucia',
    'siete',
    'sacra',
    'sajon',
    'salve',
    'salva',
    'salto',
    'salud',
    'santo',
    'santa',
    'sedar',
    'sexos',
    'segar',
    'siega',
    'siria',
    'sobar',
    'sobre',
    'solar',
    'sonda',
    'soplo',
    'soñar',
    'sudar',
    'sueño',
    'suiza',
    'sushi',
    'super',
    'tabla',
    'tacos',
    'tapas',
    'tapar',
    'tazas',
    'telon',
    'tener',
    'tejer',
    'tenis',
    'terco',
    'terca',
    'terso',
    'tersa',
    'tipos',
    'tiras',
    'todas',
    'todos',
    'tomar',
    'tonos',
    'tonto',
    'tonta',
    'toque',
    'torpe',
    'trote',
    'talar',
    'telar',
    'tarde',
    'temer',
    'tenia',
    'topar',
    'tocar',
    'tomar',
    'toser',
    'tóner',
    'traer',
    'tumba',
    'uñoso',
    'uñosa',
    'untes',
    'urbes',
    'urnas',
    'valer',
    'vacas',
    'vagos',
    'vagas',
    'valor',
    'veces',
    'vedas',
    'velas',
    'velar',
    'vemos',
    'verse',
    'verso',
    'venir',
    'verde',
    'vigor',
    'vivir',
    'volar',
    'votar',
    'vasco',
    'vasca',
    'vasto',
    'vasta',
    'viaje',
    'video',
    'weber',
    'wikis',
    'wones',
    'xolas',
    'Yemen',
    'yates',
    'yemas',
    'yendo',
    'yenes',
    'yesca',
    'yogur',
    'yugos',
    'zorro',
    'zorra',
    'zonas',
    'zurdo',
    'zurda',
    'zarca',
    'zebra',
    'zegri',
    'zeina',
    'zejel',
    'zocar',
    'zocas',
  ];
}
